# Last updated: 18th January 2018
# Following guideline set here: https://pub.dartlang.org/help#health
analyzer:
#   exclude:
#     - path/to/excluded/files/**

# Lint rules and documentation, see http://dart-lang.github.io/linter/lints
linter:
  rules:
    - camel_case_types
    - hash_and_equals
    - iterable_contains_unrelated_type
    - list_remove_unrelated_type
    - unrelated_type_equality_checks
    - valid_regexps
    - cancel_subscriptions
    - test_types_in_equals
